---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config
    default_ttl: 300
    enforce_order: True
  digitalocean:
    class: octodns_digitalocean.DigitalOceanProvider
    token: ${DO_TOKEN}
  netbox:
    class: octodns_netbox.NetboxSource
    url: https://${NETBOX_HOST}
    token: ${NETBOX_TOKEN}
    ttl: 300
    field_name: dns_name



zones:
 ${MY_DOMAIN}.:
    sources:
      - config
      - netbox
    targets:
      - digitalocean